version: "3.6"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/opt/node_app/app:delegated
            - ./package.json:/opt/node_app/app/package.json
            - ./yarn.lock:/opt/node_app/app/yarn.lock:cached
        ports:
            - "3000:3000"
        env_file:
            - .env
        tty: true
volumes:
    notused:
